server:
  port: 8082

spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  tracing:
    sampling:
      probability: 1.0 # 100% de requests esto ers requerido para activar el tracing entre micros
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:H8PVV7h2qr3AnAhpJ5vRCEHDbGP1Vm5R}
    issuer: ${JWT_ISSUER:crediya-auth}

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:crediya}
    schema: ${DB_SCHEMA:loan}
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev123}

springdoc:
  api-docs:
    path: /v3/api-docs
    format: yaml
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %clr(%5p) [traceId=%X{traceId}, spanId=%X{spanId}] %logger{36} : %msg%n"
  level:
    org.springdoc: DEBUG

adapter:
  restconsumer:
    timeout: 5000
    url: ${API_AUTH:http://localhost:8080}

resilience4j:
  circuitbreaker:
    instances:
      getUserByEmail:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
        ignore-exceptions:
          - co.com.powerup2025.model.exception.exceptions.BusinessException