server:
  port: 8081
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  tracing:
    sampling:
      probability: 1.0 # 100% de requests esto ers requerido para activar el tracing entre micros
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: crediya
    schema: loan
    username: dev_user
    password: dev123
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: "method"
    tagsSorter: "alpha"
logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
  # evita que Spring agregue el suyo
  pattern.console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %clr(%5p) [traceId=%X{traceId}, spanId=%X{spanId}] %logger{36} : %msg%n" 
   
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
resilience4j:
  circuitbreaker:
    instances:
      getUserByEmail:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
        ignore-exceptions:
          - co.com.powerup2025.model.exception.exceptions.BusinessException

